language: java
sudo: false
branches:
  only:
    - master
env:
  global:
  - secure: "WXG7TH0oswkEzJfk9L566rq/iPzVg+iqBVogjOjcs0ZeXk4oofZ8r91aRSYHP2Ee7xmQuDhDkyWMKMutcBdRoC+7+pNfkTanc2YyFpNAY4w1TqQp59d2qK0zTu8g6oWrGj82VXnrDyErb3cLN7xiwN9RVqCexV0obhHGFtNhvjA="
  - secure: "OYig3UxORxM8v5UdmljoY3to9RyJ/170ZA1btx2ZXExUkpO291V70xozM4NjRJawWSF2bGlhUM+ZtK7yCiefT5K+pAN/n7pnQnaVgcQGS5yn8SSi57l76qApY61QoCghjSIK5lsNhu01/LodWQPt4pt6SF/ZEXeaYwTuEyKzja4="
script: 
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${SFUSER} -Dsf.password=${SFPWD} deployRunNoTests || [ "${TRAVIS_PULL_REQUEST}" != "false" ]'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${SFUSER} -Dsf.password=${SFPWD} validateNoTests || [ "${TRAVIS_PULL_REQUEST}" = "false" ]'