language: java
sudo: false
branches:
  only:
    - master
env:
  global:
  - secure: "cgpBiDry3DE4SBpgxx5imXzm3rVk4IHm/QMWUddPP15TOSWDHS8bk8Q7WkVKB5BSYVPEvBBSoOoNesXg7WYc7jo0gi/laFCIJPYseJ8fKYgpLeQ/4kuuduj/fP8hFfYFitn729vi2Zdk9ViQaHjf4R1pngIcOZk9WlW9Pd9EX6o="
  - secure: "XQkUl9rUqBDCHMnX4lxeS/uKZbRzpspQPUZux2sgBFweZNZwkLkx/4sa0flIE8oSw8Bzhv3d1C+8evKWE65laRmv9VnMUNhrytPkrEUpxWa/fNkXUq+j5KWHM3Im47sH0j9itMKX4uYVA5rzY3njCSeN23K024G9koeORJDRtfA="
script: 
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${SFUSER} -Dsf.password=${SFPWD} deployRunNoTests || [ "${TRAVIS_PULL_REQUEST}" != "false" ]'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && ant -lib lib/ant-salesforce.jar -Dsf.username=${SFUSER} -Dsf.password=${SFPWD} validateNoTests || [ "${TRAVIS_PULL_REQUEST}" = "false" ]'